name: react-native-android-build-apk
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          ls
          cd apps/DocumentiveMobile
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          cd apps/DocumentiveMobile
          npm install
      - name: Build Android Release
        run: |
          ls
          cd apps/DocumentiveMobile
          yarn add expo
          expo build:android
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
